turkish = [
    'Selam', 
    'Merhaba', 
    'Nasılsın?', 
    'Günaydın', 
    'İyi akşamlar', 
    'Hoş geldin', 
    'Ne haber?', 
    'İyi misin?', 
    'Yarın buluşalım mı?', 
    'Bugün hava çok güzel', 
    'Seni özledim', 
    'Dersler nasıl gidiyor?', 
    'İşlerin yolunda mı?', 
    'Akşam yemeğe çıkalım mı?', 
    'Yeni bir film izledim, çok güzeldi!', 
    'Sınavdan yüksek not aldım!', 
    'Bu hafta çok yoğundum', 
    'Hadi kahve içmeye gidelim', 
    'Yardımına ihtiyacım var', 
    'Proje için birkaç fikrim var', 
    'Toplantıyı yarına erteleyebilir miyiz?', 
    'Trafik bugün çok yoğundu', 
    'Hafta sonu tatil planı yapalım mı?', 
    'Bilgisayarım bozuldu, tamir ettirmem lazım', 
    'Hangi kitaba başlamalıyım?', 
    'Çok güzel bir kahve yaptım!', 
    'Dün gece harika bir rüya gördüm', 
    'Bugün biraz yorgunum', 
    'Herkese selam söyle!', 
    'Yeni bir yer keşfettim, çok seversin!', 
    'Hafta sonu sinemaya gidelim mi?', 
    'Yeni bir spor yapmayı düşünüyorum', 
    'Hava soğudu, dikkat et', 
    'Online bir kursa katıldım, çok faydalı!', 
    'Uzun zamandır görüşemedik', 
    'Tatilde nereye gitmek istersin?', 
    'Şu an yoğun musun?', 
    'Biraz mola vermeliyim', 
    'Çok teşekkür ederim!', 
    'Harikasın!', 
    'Yeni bir dil öğrenmeye başladım', 
    'Bugün spor salonuna gideceğim', 
    'Alışverişe çıkmam gerekiyor', 
    'Bugün çok güzel bir haber aldım!', 
    'Dışarıda yağmur yağıyor', 
    'Telefonun sessizde kalmış olabilir mi?', 
    'Yarın sabah erken kalkmam lazım', 
    'Sonunda o kitabı bitirdim!', 
    'Çok yoğun bir hafta geçirdim', 
    'Yeni bir tarif denedim, çok lezzetli oldu'
]

english = [
    'Hello', 
    'How are you?', 
    'Good morning', 
    'Good evening', 
    'Welcome', 
    'What’s up?', 
    'Are you okay?', 
    'Shall we meet tomorrow?', 
    'The weather is amazing today', 
    'I missed you', 
    'How are your studies going?', 
    'Is everything alright at work?', 
    'Shall we go out for dinner tonight?', 
    'I watched a new movie; it was great!', 
    'I got a high grade on my exam!', 
    'It was a really busy week', 
    'Let’s grab some coffee together', 
    'I need your help', 
    'I have a few ideas for the project', 
    'Can we postpone the meeting to tomorrow?', 
    'The traffic was crazy today', 
    'Shall we plan a weekend trip?', 
    'My computer broke down; I need to get it fixed', 
    'Which book should I start with?', 
    'I made an amazing cup of coffee!', 
    'I had the most wonderful dream last night', 
    'I’m feeling a bit tired today', 
    'Say hi to everyone for me!', 
    'I found a new place you’ll love!', 
    'Let’s go to the cinema this weekend!', 
    'I’m thinking of starting a new sport', 
    'The weather is getting cold; take care', 
    'I joined an online course; it’s very useful!', 
    'It’s been a long time since we last met', 
    'Where would you like to go for vacation?', 
    'Are you busy right now?', 
    'I need to take a break', 
    'Thank you so much!', 
    'You’re amazing!', 
    'I started learning a new language', 
    'I’m going to the gym today', 
    'I need to go shopping', 
    'I received great news today!', 
    'It’s raining outside', 
    'Could your phone be on silent mode?', 
    'I need to wake up early tomorrow morning', 
    'I finally finished that book!', 
    'It’s been such a hectic week', 
    'I tried a new recipe; it turned out delicious'
]
